### ISSUE TITLE
issue-2-turn-the-car

### ISSUE THREAD

**Issue by ErikModica** [ErikModica/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] set css four directional classes with transform properties.
- [x] add function to change class based on which arrow key is pressed, and add it to an event listener for keydown.
- [x] add a transition to the car to make it look cool when a class is changed.
